# Site settings
title: Ignat Kudriavtsev
email: ignat@ignat.fi
description: Ignat Kudriavtsev homepage.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ignat.fi" # the base hostname & protocol for your site

# Aerial
your-name: Ignat Kudriavtsev
your-title: Backend Engineer
your-organisation: Posti
your-country: Finland

# Social settings
email_url: "mailto: ignat@ignat.fi"
facebook_url: https://www.facebook.com/iVerner/
github_url: https://github.com/iVerner
vk_url: https://vk.com/verner
instagram_url: https://www.instagram.com/iverner/
linkedin_url: https://www.linkedin.com/in/iverner/
twitter_url: https://twitter.com/Verner
youtube_url: https://www.youtube.com/channel/UCr8Ro-vJgIGXMwZCJ5kN5sA
telegram_url: https://t.me/Verner

# Build settings
markdown: kramdown
